// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CoinDescriptionsColumns holds the columns for the "coin_descriptions" table.
	CoinDescriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "create_at", Type: field.TypeUint32},
		{Name: "update_at", Type: field.TypeUint32},
		{Name: "delete_at", Type: field.TypeUint32},
		{Name: "app_id", Type: field.TypeUUID},
		{Name: "coin_type_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "message", Type: field.TypeString, Size: 2048},
		{Name: "used_for", Type: field.TypeString},
	}
	// CoinDescriptionsTable holds the schema information for the "coin_descriptions" table.
	CoinDescriptionsTable = &schema.Table{
		Name:       "coin_descriptions",
		Columns:    CoinDescriptionsColumns,
		PrimaryKey: []*schema.Column{CoinDescriptionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CoinDescriptionsTable,
	}
)

func init() {
}
