// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DescriptionsColumns holds the columns for the "descriptions" table.
	DescriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "coin_type_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "message", Type: field.TypeString, Size: 2048},
		{Name: "used_for", Type: field.TypeString},
	}
	// DescriptionsTable holds the schema information for the "descriptions" table.
	DescriptionsTable = &schema.Table{
		Name:       "descriptions",
		Columns:    DescriptionsColumns,
		PrimaryKey: []*schema.Column{DescriptionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "description_coin_type_id_used_for",
				Unique:  true,
				Columns: []*schema.Column{DescriptionsColumns[4], DescriptionsColumns[7]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DescriptionsTable,
	}
)

func init() {
}
