// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/project-info-manager/pkg/db/ent/coinproductinfo"
	"github.com/NpoolPlatform/project-info-manager/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// CoinProductInfoQuery is the builder for querying CoinProductInfo entities.
type CoinProductInfoQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.CoinProductInfo
	modifiers  []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CoinProductInfoQuery builder.
func (cpiq *CoinProductInfoQuery) Where(ps ...predicate.CoinProductInfo) *CoinProductInfoQuery {
	cpiq.predicates = append(cpiq.predicates, ps...)
	return cpiq
}

// Limit adds a limit step to the query.
func (cpiq *CoinProductInfoQuery) Limit(limit int) *CoinProductInfoQuery {
	cpiq.limit = &limit
	return cpiq
}

// Offset adds an offset step to the query.
func (cpiq *CoinProductInfoQuery) Offset(offset int) *CoinProductInfoQuery {
	cpiq.offset = &offset
	return cpiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cpiq *CoinProductInfoQuery) Unique(unique bool) *CoinProductInfoQuery {
	cpiq.unique = &unique
	return cpiq
}

// Order adds an order step to the query.
func (cpiq *CoinProductInfoQuery) Order(o ...OrderFunc) *CoinProductInfoQuery {
	cpiq.order = append(cpiq.order, o...)
	return cpiq
}

// First returns the first CoinProductInfo entity from the query.
// Returns a *NotFoundError when no CoinProductInfo was found.
func (cpiq *CoinProductInfoQuery) First(ctx context.Context) (*CoinProductInfo, error) {
	nodes, err := cpiq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{coinproductinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cpiq *CoinProductInfoQuery) FirstX(ctx context.Context) *CoinProductInfo {
	node, err := cpiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CoinProductInfo ID from the query.
// Returns a *NotFoundError when no CoinProductInfo ID was found.
func (cpiq *CoinProductInfoQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cpiq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{coinproductinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cpiq *CoinProductInfoQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := cpiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CoinProductInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CoinProductInfo entity is found.
// Returns a *NotFoundError when no CoinProductInfo entities are found.
func (cpiq *CoinProductInfoQuery) Only(ctx context.Context) (*CoinProductInfo, error) {
	nodes, err := cpiq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{coinproductinfo.Label}
	default:
		return nil, &NotSingularError{coinproductinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cpiq *CoinProductInfoQuery) OnlyX(ctx context.Context) *CoinProductInfo {
	node, err := cpiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CoinProductInfo ID in the query.
// Returns a *NotSingularError when more than one CoinProductInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (cpiq *CoinProductInfoQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cpiq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{coinproductinfo.Label}
	default:
		err = &NotSingularError{coinproductinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cpiq *CoinProductInfoQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := cpiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CoinProductInfos.
func (cpiq *CoinProductInfoQuery) All(ctx context.Context) ([]*CoinProductInfo, error) {
	if err := cpiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return cpiq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (cpiq *CoinProductInfoQuery) AllX(ctx context.Context) []*CoinProductInfo {
	nodes, err := cpiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CoinProductInfo IDs.
func (cpiq *CoinProductInfoQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := cpiq.Select(coinproductinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cpiq *CoinProductInfoQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := cpiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cpiq *CoinProductInfoQuery) Count(ctx context.Context) (int, error) {
	if err := cpiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return cpiq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (cpiq *CoinProductInfoQuery) CountX(ctx context.Context) int {
	count, err := cpiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cpiq *CoinProductInfoQuery) Exist(ctx context.Context) (bool, error) {
	if err := cpiq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return cpiq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (cpiq *CoinProductInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := cpiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CoinProductInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cpiq *CoinProductInfoQuery) Clone() *CoinProductInfoQuery {
	if cpiq == nil {
		return nil
	}
	return &CoinProductInfoQuery{
		config:     cpiq.config,
		limit:      cpiq.limit,
		offset:     cpiq.offset,
		order:      append([]OrderFunc{}, cpiq.order...),
		predicates: append([]predicate.CoinProductInfo{}, cpiq.predicates...),
		// clone intermediate query.
		sql:    cpiq.sql.Clone(),
		path:   cpiq.path,
		unique: cpiq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateAt uint32 `json:"create_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CoinProductInfo.Query().
//		GroupBy(coinproductinfo.FieldCreateAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (cpiq *CoinProductInfoQuery) GroupBy(field string, fields ...string) *CoinProductInfoGroupBy {
	group := &CoinProductInfoGroupBy{config: cpiq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := cpiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return cpiq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateAt uint32 `json:"create_at,omitempty"`
//	}
//
//	client.CoinProductInfo.Query().
//		Select(coinproductinfo.FieldCreateAt).
//		Scan(ctx, &v)
//
func (cpiq *CoinProductInfoQuery) Select(fields ...string) *CoinProductInfoSelect {
	cpiq.fields = append(cpiq.fields, fields...)
	return &CoinProductInfoSelect{CoinProductInfoQuery: cpiq}
}

func (cpiq *CoinProductInfoQuery) prepareQuery(ctx context.Context) error {
	for _, f := range cpiq.fields {
		if !coinproductinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cpiq.path != nil {
		prev, err := cpiq.path(ctx)
		if err != nil {
			return err
		}
		cpiq.sql = prev
	}
	if coinproductinfo.Policy == nil {
		return errors.New("ent: uninitialized coinproductinfo.Policy (forgotten import ent/runtime?)")
	}
	if err := coinproductinfo.Policy.EvalQuery(ctx, cpiq); err != nil {
		return err
	}
	return nil
}

func (cpiq *CoinProductInfoQuery) sqlAll(ctx context.Context) ([]*CoinProductInfo, error) {
	var (
		nodes = []*CoinProductInfo{}
		_spec = cpiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &CoinProductInfo{config: cpiq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if len(cpiq.modifiers) > 0 {
		_spec.Modifiers = cpiq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, cpiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cpiq *CoinProductInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cpiq.querySpec()
	if len(cpiq.modifiers) > 0 {
		_spec.Modifiers = cpiq.modifiers
	}
	_spec.Node.Columns = cpiq.fields
	if len(cpiq.fields) > 0 {
		_spec.Unique = cpiq.unique != nil && *cpiq.unique
	}
	return sqlgraph.CountNodes(ctx, cpiq.driver, _spec)
}

func (cpiq *CoinProductInfoQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := cpiq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (cpiq *CoinProductInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   coinproductinfo.Table,
			Columns: coinproductinfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: coinproductinfo.FieldID,
			},
		},
		From:   cpiq.sql,
		Unique: true,
	}
	if unique := cpiq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := cpiq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coinproductinfo.FieldID)
		for i := range fields {
			if fields[i] != coinproductinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cpiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cpiq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cpiq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cpiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cpiq *CoinProductInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cpiq.driver.Dialect())
	t1 := builder.Table(coinproductinfo.Table)
	columns := cpiq.fields
	if len(columns) == 0 {
		columns = coinproductinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cpiq.sql != nil {
		selector = cpiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cpiq.unique != nil && *cpiq.unique {
		selector.Distinct()
	}
	for _, m := range cpiq.modifiers {
		m(selector)
	}
	for _, p := range cpiq.predicates {
		p(selector)
	}
	for _, p := range cpiq.order {
		p(selector)
	}
	if offset := cpiq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cpiq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (cpiq *CoinProductInfoQuery) ForUpdate(opts ...sql.LockOption) *CoinProductInfoQuery {
	if cpiq.driver.Dialect() == dialect.Postgres {
		cpiq.Unique(false)
	}
	cpiq.modifiers = append(cpiq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return cpiq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (cpiq *CoinProductInfoQuery) ForShare(opts ...sql.LockOption) *CoinProductInfoQuery {
	if cpiq.driver.Dialect() == dialect.Postgres {
		cpiq.Unique(false)
	}
	cpiq.modifiers = append(cpiq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return cpiq
}

// CoinProductInfoGroupBy is the group-by builder for CoinProductInfo entities.
type CoinProductInfoGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cpigb *CoinProductInfoGroupBy) Aggregate(fns ...AggregateFunc) *CoinProductInfoGroupBy {
	cpigb.fns = append(cpigb.fns, fns...)
	return cpigb
}

// Scan applies the group-by query and scans the result into the given value.
func (cpigb *CoinProductInfoGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := cpigb.path(ctx)
	if err != nil {
		return err
	}
	cpigb.sql = query
	return cpigb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cpigb *CoinProductInfoGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := cpigb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (cpigb *CoinProductInfoGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(cpigb.fields) > 1 {
		return nil, errors.New("ent: CoinProductInfoGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := cpigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cpigb *CoinProductInfoGroupBy) StringsX(ctx context.Context) []string {
	v, err := cpigb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cpigb *CoinProductInfoGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cpigb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coinproductinfo.Label}
	default:
		err = fmt.Errorf("ent: CoinProductInfoGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cpigb *CoinProductInfoGroupBy) StringX(ctx context.Context) string {
	v, err := cpigb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (cpigb *CoinProductInfoGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(cpigb.fields) > 1 {
		return nil, errors.New("ent: CoinProductInfoGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := cpigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cpigb *CoinProductInfoGroupBy) IntsX(ctx context.Context) []int {
	v, err := cpigb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cpigb *CoinProductInfoGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cpigb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coinproductinfo.Label}
	default:
		err = fmt.Errorf("ent: CoinProductInfoGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cpigb *CoinProductInfoGroupBy) IntX(ctx context.Context) int {
	v, err := cpigb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (cpigb *CoinProductInfoGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(cpigb.fields) > 1 {
		return nil, errors.New("ent: CoinProductInfoGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := cpigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cpigb *CoinProductInfoGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := cpigb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cpigb *CoinProductInfoGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cpigb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coinproductinfo.Label}
	default:
		err = fmt.Errorf("ent: CoinProductInfoGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cpigb *CoinProductInfoGroupBy) Float64X(ctx context.Context) float64 {
	v, err := cpigb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (cpigb *CoinProductInfoGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(cpigb.fields) > 1 {
		return nil, errors.New("ent: CoinProductInfoGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := cpigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cpigb *CoinProductInfoGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := cpigb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cpigb *CoinProductInfoGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cpigb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coinproductinfo.Label}
	default:
		err = fmt.Errorf("ent: CoinProductInfoGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cpigb *CoinProductInfoGroupBy) BoolX(ctx context.Context) bool {
	v, err := cpigb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cpigb *CoinProductInfoGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range cpigb.fields {
		if !coinproductinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := cpigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cpigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cpigb *CoinProductInfoGroupBy) sqlQuery() *sql.Selector {
	selector := cpigb.sql.Select()
	aggregation := make([]string, 0, len(cpigb.fns))
	for _, fn := range cpigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(cpigb.fields)+len(cpigb.fns))
		for _, f := range cpigb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(cpigb.fields...)...)
}

// CoinProductInfoSelect is the builder for selecting fields of CoinProductInfo entities.
type CoinProductInfoSelect struct {
	*CoinProductInfoQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (cpis *CoinProductInfoSelect) Scan(ctx context.Context, v interface{}) error {
	if err := cpis.prepareQuery(ctx); err != nil {
		return err
	}
	cpis.sql = cpis.CoinProductInfoQuery.sqlQuery(ctx)
	return cpis.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cpis *CoinProductInfoSelect) ScanX(ctx context.Context, v interface{}) {
	if err := cpis.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (cpis *CoinProductInfoSelect) Strings(ctx context.Context) ([]string, error) {
	if len(cpis.fields) > 1 {
		return nil, errors.New("ent: CoinProductInfoSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := cpis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cpis *CoinProductInfoSelect) StringsX(ctx context.Context) []string {
	v, err := cpis.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (cpis *CoinProductInfoSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cpis.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coinproductinfo.Label}
	default:
		err = fmt.Errorf("ent: CoinProductInfoSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cpis *CoinProductInfoSelect) StringX(ctx context.Context) string {
	v, err := cpis.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (cpis *CoinProductInfoSelect) Ints(ctx context.Context) ([]int, error) {
	if len(cpis.fields) > 1 {
		return nil, errors.New("ent: CoinProductInfoSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := cpis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cpis *CoinProductInfoSelect) IntsX(ctx context.Context) []int {
	v, err := cpis.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (cpis *CoinProductInfoSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cpis.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coinproductinfo.Label}
	default:
		err = fmt.Errorf("ent: CoinProductInfoSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cpis *CoinProductInfoSelect) IntX(ctx context.Context) int {
	v, err := cpis.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (cpis *CoinProductInfoSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(cpis.fields) > 1 {
		return nil, errors.New("ent: CoinProductInfoSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := cpis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cpis *CoinProductInfoSelect) Float64sX(ctx context.Context) []float64 {
	v, err := cpis.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (cpis *CoinProductInfoSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cpis.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coinproductinfo.Label}
	default:
		err = fmt.Errorf("ent: CoinProductInfoSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cpis *CoinProductInfoSelect) Float64X(ctx context.Context) float64 {
	v, err := cpis.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (cpis *CoinProductInfoSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(cpis.fields) > 1 {
		return nil, errors.New("ent: CoinProductInfoSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := cpis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cpis *CoinProductInfoSelect) BoolsX(ctx context.Context) []bool {
	v, err := cpis.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (cpis *CoinProductInfoSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cpis.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coinproductinfo.Label}
	default:
		err = fmt.Errorf("ent: CoinProductInfoSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cpis *CoinProductInfoSelect) BoolX(ctx context.Context) bool {
	v, err := cpis.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cpis *CoinProductInfoSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := cpis.sql.Query()
	if err := cpis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
