// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/project-info-manager/pkg/db/ent/coinproductinfo"
	"github.com/google/uuid"
)

// CoinProductInfoCreate is the builder for creating a CoinProductInfo entity.
type CoinProductInfoCreate struct {
	config
	mutation *CoinProductInfoMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateAt sets the "create_at" field.
func (cpic *CoinProductInfoCreate) SetCreateAt(u uint32) *CoinProductInfoCreate {
	cpic.mutation.SetCreateAt(u)
	return cpic
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (cpic *CoinProductInfoCreate) SetNillableCreateAt(u *uint32) *CoinProductInfoCreate {
	if u != nil {
		cpic.SetCreateAt(*u)
	}
	return cpic
}

// SetUpdateAt sets the "update_at" field.
func (cpic *CoinProductInfoCreate) SetUpdateAt(u uint32) *CoinProductInfoCreate {
	cpic.mutation.SetUpdateAt(u)
	return cpic
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (cpic *CoinProductInfoCreate) SetNillableUpdateAt(u *uint32) *CoinProductInfoCreate {
	if u != nil {
		cpic.SetUpdateAt(*u)
	}
	return cpic
}

// SetDeleteAt sets the "delete_at" field.
func (cpic *CoinProductInfoCreate) SetDeleteAt(u uint32) *CoinProductInfoCreate {
	cpic.mutation.SetDeleteAt(u)
	return cpic
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (cpic *CoinProductInfoCreate) SetNillableDeleteAt(u *uint32) *CoinProductInfoCreate {
	if u != nil {
		cpic.SetDeleteAt(*u)
	}
	return cpic
}

// SetAppID sets the "app_id" field.
func (cpic *CoinProductInfoCreate) SetAppID(u uuid.UUID) *CoinProductInfoCreate {
	cpic.mutation.SetAppID(u)
	return cpic
}

// SetCoinTypeID sets the "coin_type_id" field.
func (cpic *CoinProductInfoCreate) SetCoinTypeID(u uuid.UUID) *CoinProductInfoCreate {
	cpic.mutation.SetCoinTypeID(u)
	return cpic
}

// SetProductPage sets the "product_page" field.
func (cpic *CoinProductInfoCreate) SetProductPage(s string) *CoinProductInfoCreate {
	cpic.mutation.SetProductPage(s)
	return cpic
}

// SetID sets the "id" field.
func (cpic *CoinProductInfoCreate) SetID(u uuid.UUID) *CoinProductInfoCreate {
	cpic.mutation.SetID(u)
	return cpic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (cpic *CoinProductInfoCreate) SetNillableID(u *uuid.UUID) *CoinProductInfoCreate {
	if u != nil {
		cpic.SetID(*u)
	}
	return cpic
}

// Mutation returns the CoinProductInfoMutation object of the builder.
func (cpic *CoinProductInfoCreate) Mutation() *CoinProductInfoMutation {
	return cpic.mutation
}

// Save creates the CoinProductInfo in the database.
func (cpic *CoinProductInfoCreate) Save(ctx context.Context) (*CoinProductInfo, error) {
	var (
		err  error
		node *CoinProductInfo
	)
	if err := cpic.defaults(); err != nil {
		return nil, err
	}
	if len(cpic.hooks) == 0 {
		if err = cpic.check(); err != nil {
			return nil, err
		}
		node, err = cpic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CoinProductInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cpic.check(); err != nil {
				return nil, err
			}
			cpic.mutation = mutation
			if node, err = cpic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cpic.hooks) - 1; i >= 0; i-- {
			if cpic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cpic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cpic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cpic *CoinProductInfoCreate) SaveX(ctx context.Context) *CoinProductInfo {
	v, err := cpic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cpic *CoinProductInfoCreate) Exec(ctx context.Context) error {
	_, err := cpic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cpic *CoinProductInfoCreate) ExecX(ctx context.Context) {
	if err := cpic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cpic *CoinProductInfoCreate) defaults() error {
	if _, ok := cpic.mutation.CreateAt(); !ok {
		if coinproductinfo.DefaultCreateAt == nil {
			return fmt.Errorf("ent: uninitialized coinproductinfo.DefaultCreateAt (forgotten import ent/runtime?)")
		}
		v := coinproductinfo.DefaultCreateAt()
		cpic.mutation.SetCreateAt(v)
	}
	if _, ok := cpic.mutation.UpdateAt(); !ok {
		if coinproductinfo.DefaultUpdateAt == nil {
			return fmt.Errorf("ent: uninitialized coinproductinfo.DefaultUpdateAt (forgotten import ent/runtime?)")
		}
		v := coinproductinfo.DefaultUpdateAt()
		cpic.mutation.SetUpdateAt(v)
	}
	if _, ok := cpic.mutation.DeleteAt(); !ok {
		if coinproductinfo.DefaultDeleteAt == nil {
			return fmt.Errorf("ent: uninitialized coinproductinfo.DefaultDeleteAt (forgotten import ent/runtime?)")
		}
		v := coinproductinfo.DefaultDeleteAt()
		cpic.mutation.SetDeleteAt(v)
	}
	if _, ok := cpic.mutation.ID(); !ok {
		if coinproductinfo.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized coinproductinfo.DefaultID (forgotten import ent/runtime?)")
		}
		v := coinproductinfo.DefaultID()
		cpic.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (cpic *CoinProductInfoCreate) check() error {
	if _, ok := cpic.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "CoinProductInfo.create_at"`)}
	}
	if _, ok := cpic.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New(`ent: missing required field "CoinProductInfo.update_at"`)}
	}
	if _, ok := cpic.mutation.DeleteAt(); !ok {
		return &ValidationError{Name: "delete_at", err: errors.New(`ent: missing required field "CoinProductInfo.delete_at"`)}
	}
	if _, ok := cpic.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "CoinProductInfo.app_id"`)}
	}
	if _, ok := cpic.mutation.CoinTypeID(); !ok {
		return &ValidationError{Name: "coin_type_id", err: errors.New(`ent: missing required field "CoinProductInfo.coin_type_id"`)}
	}
	if _, ok := cpic.mutation.ProductPage(); !ok {
		return &ValidationError{Name: "product_page", err: errors.New(`ent: missing required field "CoinProductInfo.product_page"`)}
	}
	return nil
}

func (cpic *CoinProductInfoCreate) sqlSave(ctx context.Context) (*CoinProductInfo, error) {
	_node, _spec := cpic.createSpec()
	if err := sqlgraph.CreateNode(ctx, cpic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (cpic *CoinProductInfoCreate) createSpec() (*CoinProductInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &CoinProductInfo{config: cpic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: coinproductinfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: coinproductinfo.FieldID,
			},
		}
	)
	_spec.OnConflict = cpic.conflict
	if id, ok := cpic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cpic.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coinproductinfo.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := cpic.mutation.UpdateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coinproductinfo.FieldUpdateAt,
		})
		_node.UpdateAt = value
	}
	if value, ok := cpic.mutation.DeleteAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coinproductinfo.FieldDeleteAt,
		})
		_node.DeleteAt = value
	}
	if value, ok := cpic.mutation.AppID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: coinproductinfo.FieldAppID,
		})
		_node.AppID = value
	}
	if value, ok := cpic.mutation.CoinTypeID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: coinproductinfo.FieldCoinTypeID,
		})
		_node.CoinTypeID = value
	}
	if value, ok := cpic.mutation.ProductPage(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coinproductinfo.FieldProductPage,
		})
		_node.ProductPage = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoinProductInfo.Create().
//		SetCreateAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoinProductInfoUpsert) {
//			SetCreateAt(v+v).
//		}).
//		Exec(ctx)
//
func (cpic *CoinProductInfoCreate) OnConflict(opts ...sql.ConflictOption) *CoinProductInfoUpsertOne {
	cpic.conflict = opts
	return &CoinProductInfoUpsertOne{
		create: cpic,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoinProductInfo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cpic *CoinProductInfoCreate) OnConflictColumns(columns ...string) *CoinProductInfoUpsertOne {
	cpic.conflict = append(cpic.conflict, sql.ConflictColumns(columns...))
	return &CoinProductInfoUpsertOne{
		create: cpic,
	}
}

type (
	// CoinProductInfoUpsertOne is the builder for "upsert"-ing
	//  one CoinProductInfo node.
	CoinProductInfoUpsertOne struct {
		create *CoinProductInfoCreate
	}

	// CoinProductInfoUpsert is the "OnConflict" setter.
	CoinProductInfoUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateAt sets the "create_at" field.
func (u *CoinProductInfoUpsert) SetCreateAt(v uint32) *CoinProductInfoUpsert {
	u.Set(coinproductinfo.FieldCreateAt, v)
	return u
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *CoinProductInfoUpsert) UpdateCreateAt() *CoinProductInfoUpsert {
	u.SetExcluded(coinproductinfo.FieldCreateAt)
	return u
}

// AddCreateAt adds v to the "create_at" field.
func (u *CoinProductInfoUpsert) AddCreateAt(v uint32) *CoinProductInfoUpsert {
	u.Add(coinproductinfo.FieldCreateAt, v)
	return u
}

// SetUpdateAt sets the "update_at" field.
func (u *CoinProductInfoUpsert) SetUpdateAt(v uint32) *CoinProductInfoUpsert {
	u.Set(coinproductinfo.FieldUpdateAt, v)
	return u
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *CoinProductInfoUpsert) UpdateUpdateAt() *CoinProductInfoUpsert {
	u.SetExcluded(coinproductinfo.FieldUpdateAt)
	return u
}

// AddUpdateAt adds v to the "update_at" field.
func (u *CoinProductInfoUpsert) AddUpdateAt(v uint32) *CoinProductInfoUpsert {
	u.Add(coinproductinfo.FieldUpdateAt, v)
	return u
}

// SetDeleteAt sets the "delete_at" field.
func (u *CoinProductInfoUpsert) SetDeleteAt(v uint32) *CoinProductInfoUpsert {
	u.Set(coinproductinfo.FieldDeleteAt, v)
	return u
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *CoinProductInfoUpsert) UpdateDeleteAt() *CoinProductInfoUpsert {
	u.SetExcluded(coinproductinfo.FieldDeleteAt)
	return u
}

// AddDeleteAt adds v to the "delete_at" field.
func (u *CoinProductInfoUpsert) AddDeleteAt(v uint32) *CoinProductInfoUpsert {
	u.Add(coinproductinfo.FieldDeleteAt, v)
	return u
}

// SetAppID sets the "app_id" field.
func (u *CoinProductInfoUpsert) SetAppID(v uuid.UUID) *CoinProductInfoUpsert {
	u.Set(coinproductinfo.FieldAppID, v)
	return u
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *CoinProductInfoUpsert) UpdateAppID() *CoinProductInfoUpsert {
	u.SetExcluded(coinproductinfo.FieldAppID)
	return u
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *CoinProductInfoUpsert) SetCoinTypeID(v uuid.UUID) *CoinProductInfoUpsert {
	u.Set(coinproductinfo.FieldCoinTypeID, v)
	return u
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *CoinProductInfoUpsert) UpdateCoinTypeID() *CoinProductInfoUpsert {
	u.SetExcluded(coinproductinfo.FieldCoinTypeID)
	return u
}

// SetProductPage sets the "product_page" field.
func (u *CoinProductInfoUpsert) SetProductPage(v string) *CoinProductInfoUpsert {
	u.Set(coinproductinfo.FieldProductPage, v)
	return u
}

// UpdateProductPage sets the "product_page" field to the value that was provided on create.
func (u *CoinProductInfoUpsert) UpdateProductPage() *CoinProductInfoUpsert {
	u.SetExcluded(coinproductinfo.FieldProductPage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CoinProductInfo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coinproductinfo.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CoinProductInfoUpsertOne) UpdateNewValues() *CoinProductInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(coinproductinfo.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.CoinProductInfo.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *CoinProductInfoUpsertOne) Ignore() *CoinProductInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoinProductInfoUpsertOne) DoNothing() *CoinProductInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoinProductInfoCreate.OnConflict
// documentation for more info.
func (u *CoinProductInfoUpsertOne) Update(set func(*CoinProductInfoUpsert)) *CoinProductInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoinProductInfoUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateAt sets the "create_at" field.
func (u *CoinProductInfoUpsertOne) SetCreateAt(v uint32) *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.SetCreateAt(v)
	})
}

// AddCreateAt adds v to the "create_at" field.
func (u *CoinProductInfoUpsertOne) AddCreateAt(v uint32) *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.AddCreateAt(v)
	})
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *CoinProductInfoUpsertOne) UpdateCreateAt() *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.UpdateCreateAt()
	})
}

// SetUpdateAt sets the "update_at" field.
func (u *CoinProductInfoUpsertOne) SetUpdateAt(v uint32) *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.SetUpdateAt(v)
	})
}

// AddUpdateAt adds v to the "update_at" field.
func (u *CoinProductInfoUpsertOne) AddUpdateAt(v uint32) *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.AddUpdateAt(v)
	})
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *CoinProductInfoUpsertOne) UpdateUpdateAt() *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.UpdateUpdateAt()
	})
}

// SetDeleteAt sets the "delete_at" field.
func (u *CoinProductInfoUpsertOne) SetDeleteAt(v uint32) *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.SetDeleteAt(v)
	})
}

// AddDeleteAt adds v to the "delete_at" field.
func (u *CoinProductInfoUpsertOne) AddDeleteAt(v uint32) *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.AddDeleteAt(v)
	})
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *CoinProductInfoUpsertOne) UpdateDeleteAt() *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.UpdateDeleteAt()
	})
}

// SetAppID sets the "app_id" field.
func (u *CoinProductInfoUpsertOne) SetAppID(v uuid.UUID) *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *CoinProductInfoUpsertOne) UpdateAppID() *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.UpdateAppID()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *CoinProductInfoUpsertOne) SetCoinTypeID(v uuid.UUID) *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *CoinProductInfoUpsertOne) UpdateCoinTypeID() *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.UpdateCoinTypeID()
	})
}

// SetProductPage sets the "product_page" field.
func (u *CoinProductInfoUpsertOne) SetProductPage(v string) *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.SetProductPage(v)
	})
}

// UpdateProductPage sets the "product_page" field to the value that was provided on create.
func (u *CoinProductInfoUpsertOne) UpdateProductPage() *CoinProductInfoUpsertOne {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.UpdateProductPage()
	})
}

// Exec executes the query.
func (u *CoinProductInfoUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoinProductInfoCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoinProductInfoUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CoinProductInfoUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CoinProductInfoUpsertOne.ID is not supported by MySQL driver. Use CoinProductInfoUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CoinProductInfoUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CoinProductInfoCreateBulk is the builder for creating many CoinProductInfo entities in bulk.
type CoinProductInfoCreateBulk struct {
	config
	builders []*CoinProductInfoCreate
	conflict []sql.ConflictOption
}

// Save creates the CoinProductInfo entities in the database.
func (cpicb *CoinProductInfoCreateBulk) Save(ctx context.Context) ([]*CoinProductInfo, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cpicb.builders))
	nodes := make([]*CoinProductInfo, len(cpicb.builders))
	mutators := make([]Mutator, len(cpicb.builders))
	for i := range cpicb.builders {
		func(i int, root context.Context) {
			builder := cpicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CoinProductInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cpicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = cpicb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cpicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cpicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cpicb *CoinProductInfoCreateBulk) SaveX(ctx context.Context) []*CoinProductInfo {
	v, err := cpicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cpicb *CoinProductInfoCreateBulk) Exec(ctx context.Context) error {
	_, err := cpicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cpicb *CoinProductInfoCreateBulk) ExecX(ctx context.Context) {
	if err := cpicb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoinProductInfo.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoinProductInfoUpsert) {
//			SetCreateAt(v+v).
//		}).
//		Exec(ctx)
//
func (cpicb *CoinProductInfoCreateBulk) OnConflict(opts ...sql.ConflictOption) *CoinProductInfoUpsertBulk {
	cpicb.conflict = opts
	return &CoinProductInfoUpsertBulk{
		create: cpicb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoinProductInfo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cpicb *CoinProductInfoCreateBulk) OnConflictColumns(columns ...string) *CoinProductInfoUpsertBulk {
	cpicb.conflict = append(cpicb.conflict, sql.ConflictColumns(columns...))
	return &CoinProductInfoUpsertBulk{
		create: cpicb,
	}
}

// CoinProductInfoUpsertBulk is the builder for "upsert"-ing
// a bulk of CoinProductInfo nodes.
type CoinProductInfoUpsertBulk struct {
	create *CoinProductInfoCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CoinProductInfo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coinproductinfo.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CoinProductInfoUpsertBulk) UpdateNewValues() *CoinProductInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(coinproductinfo.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CoinProductInfo.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *CoinProductInfoUpsertBulk) Ignore() *CoinProductInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoinProductInfoUpsertBulk) DoNothing() *CoinProductInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoinProductInfoCreateBulk.OnConflict
// documentation for more info.
func (u *CoinProductInfoUpsertBulk) Update(set func(*CoinProductInfoUpsert)) *CoinProductInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoinProductInfoUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateAt sets the "create_at" field.
func (u *CoinProductInfoUpsertBulk) SetCreateAt(v uint32) *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.SetCreateAt(v)
	})
}

// AddCreateAt adds v to the "create_at" field.
func (u *CoinProductInfoUpsertBulk) AddCreateAt(v uint32) *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.AddCreateAt(v)
	})
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *CoinProductInfoUpsertBulk) UpdateCreateAt() *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.UpdateCreateAt()
	})
}

// SetUpdateAt sets the "update_at" field.
func (u *CoinProductInfoUpsertBulk) SetUpdateAt(v uint32) *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.SetUpdateAt(v)
	})
}

// AddUpdateAt adds v to the "update_at" field.
func (u *CoinProductInfoUpsertBulk) AddUpdateAt(v uint32) *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.AddUpdateAt(v)
	})
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *CoinProductInfoUpsertBulk) UpdateUpdateAt() *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.UpdateUpdateAt()
	})
}

// SetDeleteAt sets the "delete_at" field.
func (u *CoinProductInfoUpsertBulk) SetDeleteAt(v uint32) *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.SetDeleteAt(v)
	})
}

// AddDeleteAt adds v to the "delete_at" field.
func (u *CoinProductInfoUpsertBulk) AddDeleteAt(v uint32) *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.AddDeleteAt(v)
	})
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *CoinProductInfoUpsertBulk) UpdateDeleteAt() *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.UpdateDeleteAt()
	})
}

// SetAppID sets the "app_id" field.
func (u *CoinProductInfoUpsertBulk) SetAppID(v uuid.UUID) *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *CoinProductInfoUpsertBulk) UpdateAppID() *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.UpdateAppID()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *CoinProductInfoUpsertBulk) SetCoinTypeID(v uuid.UUID) *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *CoinProductInfoUpsertBulk) UpdateCoinTypeID() *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.UpdateCoinTypeID()
	})
}

// SetProductPage sets the "product_page" field.
func (u *CoinProductInfoUpsertBulk) SetProductPage(v string) *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.SetProductPage(v)
	})
}

// UpdateProductPage sets the "product_page" field to the value that was provided on create.
func (u *CoinProductInfoUpsertBulk) UpdateProductPage() *CoinProductInfoUpsertBulk {
	return u.Update(func(s *CoinProductInfoUpsert) {
		s.UpdateProductPage()
	})
}

// Exec executes the query.
func (u *CoinProductInfoUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CoinProductInfoCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoinProductInfoCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoinProductInfoUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
