// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CoinDescription is the predicate function for coindescription builders.
type CoinDescription func(*sql.Selector)

// CoinProductInfo is the predicate function for coinproductinfo builders.
type CoinProductInfo func(*sql.Selector)
