// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Description is the predicate function for description builders.
type Description func(*sql.Selector)
